version: '2.0'
services:
  practica-web:
    build:
      context: ./
      dockerfile: docker/web.docker
    restart: always
    ports:
      - "80:80"
    volumes:
     - .:/var/www
  practica-app:
    build:
      context: ./
      dockerfile: docker/app.docker
    ports:
      - "9000"
    volumes:
      - .:/var/www
  practica-mysql:
    container_name: "practica-mysql"
    build:
      context: ./
      dockerfile: docker/mysql.docker
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=practica"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - data_mysql:/var/lib/mysql
volumes:
  data_mysql: